# SPDX-FileCopyrightText: 2026 Ghostwriter Mojikumi contributors
# SPDX-License-Identifier: BSD-2-Clause

[General]
displayName = Ghostwriter Mojikumi
description = Ghostwriter with CJK mojikumi support
webpage = https://github.com/Mr-Drinking/Ghostwriter-Mojikumi
