# SPDX-FileCopyrightText: 2026 Ghostwriter Mojikumi contributors
# SPDX-License-Identifier: BSD-2-Clause

[General]
displayName = Ghostwriter Mojikumi
description = Local Craft blueprints for Ghostwriter Mojikumi release artifacts
webpage = https://github.com/Mr-Drinking/Ghostwriter-Mojikumi

